readme.md
Add Moon.svg without Try it! 😄 
---
Add real-time moon on your github profile!  
Moon.svg shows the current moon phase in real time!
📍 For example :  
<a href="https://moon-svg.minung.dev">
</a>
<a href="https://moon-svg.minung.dev">
</a>
=> Add Moon.svg (Deleted Try it)

readme.md
[Peerlist](https://peerlist.io/) is a community of working professionals focused on building a personal brand, sharing professional content, and finding peers to collaborate with. A [Peerlist profile](https://peerlist.io/vinitshahdeo) can be used as a simple resume or a complete portfolio to showcase your work. You can style your GitHub Profile `README.md` with an awesome Peerlist markdown badge.
```
```
[![Peerlist](https://peerlist-readme-badge.herokuapp.com/api/vinitshahdeo)](https://peerlist.io/vinitshahdeo)
> Learn more [here](https://github.com/vinitshahdeo/peerlist-readme-badge)
=> Add Peerlist Badge for GitHub Profile `README.md`

readme.md
I added my GitHub Action to display your last games on Chess.com at the bottom of the list, I hope it's ok!
=> Added Chess.com Games and Stats action

readme.md, spotify-data-card.svg
Adds the Spotify Data Card tool to the "Widgets" section and also adds a "Table of Contents" section
=> Add Spotify Data Card and table of contents

readme.md
Topmate is a platform to connect 1:1 with your audience & monetise your time better. Basically, one link to do it all ➥ [topmate.io/vinitshahdeo](https://topmate.io/vinitshahdeo). Even better, you can now add a markdown badge in your GitHub profile README to connect with your community!
[![Topmate](https://topmate-readme-badge.herokuapp.com/vinitshahdeo)](https://topmate.io/vinitshahdeo)
➥ Try it out here: [topmate-readme-badge.netlify.app](https://topmate-readme-badge.netlify.app/)
<a href="https://www.producthunt.com/posts/topmate-io-readme-badge-generator?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-topmate&#0045;io&#0045;readme&#0045;badge&#0045;generator" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=365190&theme=light" …
=> Add Topmate badge

readme.md
GitHub action to show your latest YouTube videos on your GitHub profile or project readme automatically as dynamic SVG cards
<br/>
=> Add GitHub Readme YouTube Cards

readme.md
structure:  Widgets -> 67. GIFs For GitHub
`Name:`
GIFs For GitHub
`Description:`
Awesome List of GIFs & avatars to use in GitHub markdown
`Examples used:`
=> add: GIFs for Readme

readme.md
Track your GitHub profile views and analyze statistics.
📍 For example :
[![Yaroslav Podorvanov profile views](https://github.com/u8views/go-u8views/blob/main/public/assets/images/yaroslav-podorvanov-developer.jpg?raw=true)](https://u8views.com/github/YaroslavPodorvanov)
=> Yet another profile views counter https://u8views.com/

readme.md
Added Lanyard Profile Readme.
A tool to display your discord rich presence on github profile.
🏷️ Utilize Lanyard to display your Discord Presence in your GitHub Profile.
=> Added a New Widget

readme.md
Added another New Widget
⭐ Plot your repo stars over time!
=> Another Star Chart Widget

readme.md
Shout-out supporters in your GitHub README file.
<br/>
Stargazers &nbsp;
Forkers &nbsp;
=> Added New widget

readme.md
Another Cute View Counter.
<br/>
It's kinda childish, but what's over.
=> Added Moe Counter Widget

readme.md
Added Star History and M3 Markdown Badges
FIxed the Moe Counter and U8Views
=> Some Fixes and Additions

readme.md
=> docs: Updated readme

readme.md
=> docs(widgets): add github-stats

readme.md
=> docs(widgets): add github repo contribution stats

readme.md
=> docs(widgets): add code-statistic

readme.md
=> docs(badges): add u8views

readme.md
=> docs: add bentohub

readme.md
=> docs(badges): combine u8 entries

readme.md
=> docs(badges): add stardev

readme.md
=> docs(badges): delete youtube stats and gitwar

readme.md
=> docs(widgets): delete github readme twitter

readme.md
=> docs(widgets): replace leetcode-stats with leetcode-stats-card

readme.md
=> docs(widgets): add github-profile-repo-analytics

readme-fa.md, readme.md
درود وقت بخیر
متن به فارسی ترجمه شده است.
لطفا یک نگاه کلی بندازید.
و اینکه یکه تولید کننده استک توی ترجمه مشکل داشتم. (خط 1244 )
تمامی بخش ها هم ترجمه شده.
=> Persian Translation

readme.md
=> feat: add devimg

readme.md
- Link still works, but username has been changed.
=> fix: update username for goodreads url
